### ISSUE TITLE
Multiple repo roots

### ISSUE THREAD

**Issue by petar** [kocircuit/kocircuit#5]
Support multiple colon-separated repo roots in KOPATH, searched in the order given.
This generalizes the notion of having a separate KOROOT and KOPATH variables.

**Comment by ewoutp** [comment]
Multiple roots will be helpful anyway. Still believe a separate root (ala go) will be useful as well, both for library as well as tool locations (as soon as we have tools like `ko fmt`, `kodoc` etc)

**Comment by mewmew** [comment]
This hit me today, when trying out the hello world example.

```bash
$ go get github.com/kocircuit/kocircuit/lang/ko
$ ko play github.com/kocircuit/kocircuit/codelab/HelloWorld
(kocircuit/lang/go/sys/compile.go:31) (ko/R0) compiled functions=0 steps=0 steps-per-function=0.00
cannot find main circuit github.com/kocircuit/kocircuit/codelab/HelloWorld
$ echo $GOPATH
/home/u/goget:/home/u/Desktop/go
$ set GOPATH /home/u/goget
$ echo $GOPATH
/home/u/goget
$ ko play github.com/kocircuit/kocircuit/codelab/HelloWorld
(kocircuit/lang/go/sys/compile.go:31) (ko/R0) compiled functions=1 steps=2 steps-per-function=2.00
"Hello, world!"
```
